### ISSUE TITLE
Enemy AI

### ISSUE THREAD

**Issue by Cheeseless** [aagavin/305-3D-Game#10]
Dumb chase AI is fine for a start, but it'd be lovely to have it be able to go around obstacles.

**Comment by aagavin** [comment]
What about it just bounces off a walls and if it sees the player then it runs towards the player?

**Comment by Cheeseless** [comment]
That works.

**Comment by aagavin** [comment]
I'm going to hold of on this till next class because Tom said that we were going to cover this
